version: 2

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: true
  python:
    version: 3.12
    install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
      - method: pip
        path: .
  theme:
    name: sphinx_rtd_theme
    version: latest
